Repository lblod/ember-rdfa-editor-template-variable-plugin, pull requests merged in 2022-09, with the labels that each got.

#15 chore(deps): bump editor to v0.62.0
  package-lock.json
  package.json
  tests/dummy/app/templates/application.hbs
Labels: internal

#16 build(ci): Update drone ember-cli version to 3.28.5
  .drone.yml
  config/ember-try.js
  package-lock.json
  package.json
Labels: internal

#17 chore(deps)!: bump editor to v0.63.1
  app/styles/app.scss
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: breaking

#18 get the endpoint from the codelist
  addon/components/editor-plugins/template-variable-card.js
  tests/dummy/app/controllers/application.js
Labels: enhancement, breaking

#20 fix(init): remove broken and useless modelwritten handler
  addon/template-variable-plugin.js
Labels: bug

#22 fix(selection-handler): handle cases where selection is empty
  addon/components/editor-plugins/template-variable-card.js
Labels: bug

#23 handle cases with empty selection
  addon/components/editor-plugins/template-variable-card.js
Labels: bug
